"""migration

Revision ID: 10795f26d638
Revises: 06ee0261edf2
Create Date: 2022-11-22 17:54:00.048683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10795f26d638'
down_revision = '06ee0261edf2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
