"""migration

Revision ID: 2aff8df60e6e
Revises: 10795f26d638
Create Date: 2022-11-22 17:55:11.403385

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2aff8df60e6e'
down_revision = '10795f26d638'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('konten', sa.Column('kelas', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_foreign_key(None, 'konten', 'kelas', ['kelas'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'konten', type_='foreignkey')
    op.drop_column('konten', 'kelas')
    # ### end Alembic commands ###
