"""migration

Revision ID: 40a38f90e8a7
Revises: b9f627d8cfbd
Create Date: 2022-11-24 09:45:02.114080

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '40a38f90e8a7'
down_revision = 'b9f627d8cfbd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('konten', sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_foreign_key(None, 'konten', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'konten', type_='foreignkey')
    op.drop_column('konten', 'user_id')
    # ### end Alembic commands ###
