"""migration

Revision ID: 49b2a20c7522
Revises: 7727bb2994e5
Create Date: 2022-11-22 10:31:08.894899

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "49b2a20c7522"
down_revision = "7727bb2994e5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "konten",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kelas_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("photo_id", sa.Integer, nullable=True),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("release_date", sa.String(), nullable=True),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("synopsis", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["kelas_id"],
            ["kelas.id"],
        ),
        sa.ForeignKeyConstraint(
            ["photo_id"],
            ["media.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_konten_id"), "konten", ["id"], unique=False)
    op.create_table(
        "tugas",
        sa.Column("id", sa.String(length=15), nullable=False),
        sa.Column("kelas_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("deadline", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("update_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["kelas_id"],
            ["kelas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tugas_id"), "tugas", ["id"], unique=False)
    op.create_table(
        "comment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("konten_id", sa.Integer(), nullable=True),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("release_date", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["konten_id"],
            ["konten.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_comment_id"), "comment", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_comment_id"), table_name="comment")
    op.drop_table("comment")
    op.drop_index(op.f("ix_tugas_id"), table_name="tugas")
    op.drop_table("tugas")
    op.drop_index(op.f("ix_konten_id"), table_name="konten")
    op.drop_table("konten")
    # ### end Alembic commands ###
