"""migration

Revision ID: b9f627d8cfbd
Revises: eedcb2784568
Create Date: 2022-11-23 08:08:43.527054

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b9f627d8cfbd'
down_revision = 'eedcb2784568'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comment_user_id_fkey', 'comment', type_='foreignkey')
    op.drop_column('comment', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('comment_user_id_fkey', 'comment', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
