"""migration

Revision ID: bfcec5df63ba
Revises: 2aff8df60e6e
Create Date: 2022-11-22 17:57:45.224373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfcec5df63ba'
down_revision = '2aff8df60e6e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
