"""migration

Revision ID: eedcb2784568
Revises: bfcec5df63ba
Create Date: 2022-11-23 08:07:59.406224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eedcb2784568'
down_revision = 'bfcec5df63ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comment_konten_id_fkey', 'comment', type_='foreignkey')
    op.drop_column('comment', 'konten_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('konten_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('comment_konten_id_fkey', 'comment', 'konten', ['konten_id'], ['id'])
    # ### end Alembic commands ###
