"""migration

Revision ID: 426f11e45107
Revises: 49e811e56ca8
Create Date: 2022-12-16 21:12:27.187647

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '426f11e45107'
down_revision = '49e811e56ca8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('konten_kelas_fkey', 'konten', type_='foreignkey')
    op.drop_column('konten', 'kelas')
    op.add_column('lessons', sa.Column('deskripsi', sa.String(), nullable=False))
    op.add_column('tugas', sa.Column('lesson_id', sa.Integer(), nullable=True))
    op.drop_constraint('tugas_kelas_id_fkey', 'tugas', type_='foreignkey')
    op.create_foreign_key(None, 'tugas', 'lessons', ['lesson_id'], ['id'])
    op.drop_column('tugas', 'kelas_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tugas', sa.Column('kelas_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tugas', type_='foreignkey')
    op.create_foreign_key('tugas_kelas_id_fkey', 'tugas', 'kelas', ['kelas_id'], ['id'])
    op.drop_column('tugas', 'lesson_id')
    op.drop_column('lessons', 'deskripsi')
    op.add_column('konten', sa.Column('kelas', postgresql.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('konten_kelas_fkey', 'konten', 'kelas', ['kelas'], ['id'])
    # ### end Alembic commands ###
