"""migration

Revision ID: 4cac3eac802d
Revises: 788e47d64494
Create Date: 2022-12-16 08:19:57.246736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cac3eac802d'
down_revision = '788e47d64494'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
