"""migration

Revision ID: 788e47d64494
Revises: 16f8f68febe5
Create Date: 2022-12-13 19:20:36.503773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '788e47d64494'
down_revision = '16f8f68febe5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('type', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'type')
    # ### end Alembic commands ###
